# Generated by Django 3.0.7 on 2020-06-27 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200627_0112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='refund',
            name='purchase_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Purchase'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
