# Generated by Django 3.0.7 on 2020-07-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200627_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='confirmation',
            field=models.BooleanField(null=True),
        ),
    ]
