# Generated by Django 3.0.7 on 2020-07-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200701_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='refund',
            name='confirmation',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
