# Generated by Django 3.0.7 on 2020-07-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200701_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='make_refund_status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
