# Generated by Django 3.0.7 on 2020-07-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_purchase_make_refund_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='make_refund_status',
            field=models.BooleanField(default=False),
        ),
    ]
